import numpy as np

temperature = [34.2, 36.5, 33.1, 35.0, 37.8]
average = np.mean(temperature)
print(average)

#NUMPY STAN FOR NUMERICAL PYTHON!! ---USING OF ARRAY

'''
BBENIFITS OF NUMPY ARRAY OVER LIST
1. FASTER THAN LIST
2. MORE COMPACT THAN LIST
3. CONVENIENT THAN LIST
4. MORE EFFICIENT THAN LIST
5. NUMPY ARRAY HAVE MORE FUNCTION THAN LIST
6. NUMPY ARRAY ARE EASIER TO USE THAN LIST
'''

#USING OF NUMPY:
'''
DATA SCIENCE MACHINE LEARNING ARTIFICIAL INTELLIGENCE DEEP LEARNING
STOCK MARKET PREDICITION, WHEARHER PREDICTION, SALES PREDICTION
IMAGE PROCESSING, DATA ANALYSIS, DATA VISUALIZATION
MEDICAL FIELD 
'''


#DIFFRENCE BETWEEN LIST AND NUMPY ARRAY:

"""
NUMPY ARRAYS ARE FASTER, MORE COMPACT, AND MORE CONVENIENT THAN LISTS. THEY ALSO HAVE MORE FUNCTIONS AND ARE EASIER TO USE FOR NUMERICAL COMPUTATIONS.
MEMORY USAGE: NUMPY ARRAYS USE LESS MEMORY THAN LISTS.
PERFORMANCE: NUMPY ARRAYS ARE FASTER THAN LISTS FOR NUMERICAL OPERATIONS
SAMLL DATA FOR LIST AND LARGE DATA FOR NUMPY ARRAY

"""